services:
  hermes_db:
    image: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file: .env.docker
    ports:
      - "5432:5432"

  hermes_redis:
    image: redis

  hermes_api:
    build:
      context: .
      dockerfile: ./Dockerfile.api
    entrypoint: ./entrypoint.sh
    depends_on:
      - hermes_db
    env_file: .env.docker
    ports:
      - "8000:8000"

  # Scrapy + worker + beat
  hermes_scrapper:
    build:
      context: .
      dockerfile: ./Dockerfile.crawler
    env_file: .env.docker
    command: celery -A tasks.celery_app worker -B -l INFO
    depends_on:
      - hermes_db
      - hermes_redis

volumes:
  pgdata:
