FROM python:3.12-slim
ENV POETRY_VIRTUALENVS_CREATE=false

WORKDIR /usr/src/app

RUN pip install poetry

COPY ./api ./
COPY ./core ./core/
COPY ./migrations ./migrations/
COPY ./pyproject.toml ./
COPY ./poetry.lock ./
COPY ./alembic.ini ./
COPY ./entrypoint.sh ./
RUN chmod +x ./entrypoint.sh

RUN poetry config installer.max-workers 10
RUN poetry install --no-interaction --no-ansi --no-root --with api,core

EXPOSE 8000

