FROM python:3.12-slim
ENV POETRY_VIRTUALENVS_CREATE=false

WORKDIR /usr/src/app

RUN pip install poetry

COPY ./api ./api/
COPY ./core ./core/
COPY ./migrations ./migrations/
COPY ./pyproject.toml ./
COPY ./poetry.lock ./
COPY ./alembic.ini ./
COPY ./entrypoint.sh ./
RUN chmod +x ./entrypoint.sh

ENV POETRY_REQUESTS_TIMEOUT=300
RUN poetry config installer.max-workers 10
RUN poetry install --no-interaction --no-ansi --no-root --without dev,crawler,celery

EXPOSE 8000

